version: "3.9"
name: "dating-app"
services:
        zookeeper:
            image: confluentinc/cp-zookeeper:latest
            environment:
              ZOOKEEPER_CLIENT_PORT: 2181
              ZOOKEEPER_TICK_TIME: 2000
            ports:
              - 2181:2181
            networks:
             - app-network
        kafka:
            image: confluentinc/cp-kafka:latest
            depends_on:
              - zookeeper
            ports:
              - 9092:9092
            environment:
              KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
              KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
              KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
              KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
              KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
              KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
              KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            networks:
             - app-network
        mongo:
            container_name: mongo
            image: mongo
            volumes:
              - ./data:/data/db
            ports:
              - '27017:27017'
            networks:
              - app-network
        dating-app:
           build:
             context: ./
           volumes:
             - ./:/usr/src/app
             - /usr/src/app/node_modules
           command:
             - nodemon
             - --legacy-watch
             - app.js
           container_name: dating-app-container
           image: dating-app-backend
           restart: always
           ports:
             - "3000:3000"
           links:
             - mongo
             - kafka
           networks:
             - app-network
networks:
  app-network: