openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user registration, login, and token refresh functionalities.
servers:
  - url: "http://localhost:3000/api"
    description: Development server
paths:
  /auth/register:
    $ref: "./paths/auth.yaml#/~1register-user"
  /auth/otp/generate:
    $ref: "./paths/auth.yaml#/~1generate-signin-otp"
  /auth/otp/verify:
    $ref: "./paths/auth.yaml#/~1verify-signin-otp"
  /auth/token/refresh:
    $ref: "./paths/auth.yaml#/~1refresh-token"
  /auth/logout:
    $ref: "./paths/auth.yaml#/~1logout"

  /profile/upload-image:
    $ref: "./paths/profile.yaml#/~1upload-profile-picture"
components:
  schemas:
    User:
      $ref: "./components/schemas/User.yaml"
  responses:
    BadRequest:
      $ref: "./components/responses/BadRequest.yaml"
    Unauthorized:
      $ref: "./components/responses/Unauthorized.yaml"
  securitySchemes:
    $ref: "./components/security/bearer.yaml"
