openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user registration, login, and token refresh functionalities.
servers:
  - url: "http://localhost:3000/api"
    description: Development server
paths:
  /auth/register:
    $ref: "./paths/registerUser.yaml"
  /auth/login:
    $ref: "./paths/loginUser.yaml"
  /auth/token/refresh:
    $ref: "./paths/refreshToken.yaml"
components:
  schemas:
    User:
      $ref: "./components/schemas/User.yaml"
  responses:
    BadRequest:
      $ref: "./components/responses/BadRequest.yaml"
    Unauthorized:
      $ref: "./components/responses/Unauthorized.yaml"
  securitySchemes:
    $ref: "./components/security/bearer.yaml"
